void LHEMassdumper(TString Model, TString mT, TString mX) {

  // From https://root.cern.ch/root/html/tutorials/tree/copytree3.C.html
  // void copytree3
  // Example of Root macro to copy a subset of a Tree to a new Tree
  // Only selected entries are copied to the new Tree.
  // The input file has been generated by the program in $ROOTSYS/test/Event
  // with   Event 1000 1 99 1
  //Author: Rene Brun

   gSystem->Load("$ROOTSYS/test/libEvent");

   TString mainDiskArea = "/eos/user/s/scodella/Stop/LatinoTrees/";

   Model.ReplaceAll("_Ext1", "");	

   TString inputName = mainDiskArea + "latino" + Model;

   TChain oldtree("latino");

   int nFiles = -1;
   if (Model=="_T2tt_mStop-150to250") nFiles = 28;
   if (Model=="_T2tt_mStop-250to350") nFiles = 30;
   if (Model=="_T2tt_mStop-350to400") nFiles = 28;
   if (Model=="_T2tt_mStop-400to1200") nFiles = 27;
   if (Model=="_T2bW") nFiles = 28;
   if (Model=="_TChiWW") nFiles = 3;
   if (Model=="_TChiWW_mChi1") nFiles = 1;
   if (Model=="_TChiWW_mChi1bis") nFiles = 1;
   if (Model=="_TChiWW_mChi1ter") nFiles = 1;
   if (Model=="_TChiSlep") nFiles = 4;
   if (Model=="_TChiSlepExt") nFiles = 4;

   for (int fl = 0; fl<nFiles; fl++) {

     //Get old file, old tree and set top branch address
     TString fileName = inputName; 
     if (nFiles>1) { fileName += "__part"; fileName += fl; }
     fileName += ".root";
     oldtree.Add(fileName);
     //TFile *oldfile = new TFile(fileName, "read");
     //TTree *oldtree = (TTree*)oldfile->Get("latino");
   
   }
   
   Long64_t nentries = oldtree.GetEntries();

   float susyM, susyMLSP; UInt_t event;
   vector<float>   *std_vector_GEN_weight; std_vector_GEN_weight = 0;
   if (Model.Contains("T2")) oldtree.SetBranchAddress("susyMstop", &susyM);
   if (Model.Contains("TChi")) oldtree.SetBranchAddress("susyMChargino", &susyM);
   oldtree.SetBranchAddress("susyMLSP",    &susyMLSP);
   oldtree.SetBranchAddress("event",       &event);
   oldtree.SetBranchAddress("std_vector_GEN_weight",   &std_vector_GEN_weight);
   
   //Create a new file + a clone of old tree in new file
   TString outputName = mainDiskArea + "latino" + Model + "_Sm" + mT + "_Xm" + mX + ".root";
   if (Model.Contains("TChi")) outputName.ReplaceAll("_Sm", "_Xm");
   TFile *newfile = new TFile(outputName,"recreate");
   TTree *newtree = oldtree.CloneTree(0);

   TH1D *SumGenWeights = new TH1D("SumGenWeights", "", 250, 0., 250.);

   TString skimName;
   if (Model.Contains("T2")) 
     skimName = "/eos/user/s/scodella/Stop/LatinoSkims/Feb2017_Summer16_stop_ghent_others/MCl2stop__SFWeights__hadd/latino" + Model + ".root";
   else if (Model.Contains("TChi")) 
     skimName = "/eos/cms/store/caf/user/scodella/BTV/Feb2017_Summer16_stop_ghent_others_isr/MCl2stop__SFWeights__hadd/latino" + Model + ".root";
   TFile *skimfile = new TFile(skimName, "read");
   TTree *skimtree = (TTree*)skimfile->Get("latino");
   UInt_t event2; float susyM2, susyMLSP2;
   if (Model.Contains("T2")) skimtree->SetBranchAddress("susyMstop", &susyM2);
   if (Model.Contains("TChi")) skimtree->SetBranchAddress("susyMChargino", &susyM2);
   skimtree->SetBranchAddress("event",       &event2);
   skimtree->SetBranchAddress("susyMLSP",    &susyMLSP2);
   Long64_t nentries2 = skimtree->GetEntries();
   
   vector<int> skimmedEvents; skimmedEvents.clear();
   for (Long64_t i=0;i<nentries2; i++) {
     if (i%(nentries2/10)==0) cout << int( (1.*i)/nentries2*100. + 0.1 ) << "% " << endl;
     skimtree->GetEntry(i);
     if (susyM2==mT.Atoi() && susyMLSP2==mX.Atoi())
       skimmedEvents.push_back(event2);
   }
   
   for (Long64_t i=0;i<nentries; i++) {

     if (i%(nentries/10)==0) cout << int( (1.*i)/nentries*100. + 0.1 ) << "% " << endl;
     
     oldtree.GetEntry(i);
     
     if (susyM==mT.Atoi() && susyMLSP==mX.Atoi()) {
     
       for (int gw = 0; gw<250; gw++) 
	 SumGenWeights->Fill(gw+0.5, std_vector_GEN_weight->at(gw));

       for (int se = 0; se<skimmedEvents.size(); se++)
	 if (skimmedEvents.at(se)==event) newtree->Fill();

     }
     
   }
   
   newfile->cd();

   SumGenWeights->Write();

   newtree->Print();
   newtree->AutoSave();

   skimfile->Close();
   //oldfile->Close();
   newfile->Close();
   
}

void LHEdumper(TString Model = "", TString mT = "", TString mX = "") {

  cout << "    LHEdumper " << Model << " " << mT << " " << mX << endl; 

  if (Model=="") Model = gSystem->Getenv("MODEL");

  cout << "      " << Model << endl; 

  if (mT=="") {

    TString MassPoint = gSystem->Getenv("MASSPOINT");
 
    MassPoint.ReplaceAll("#", ""); 

    cout << "      " << MassPoint << endl; 

    TString StopMass = MassPoint;
    StopMass.Replace(0, StopMass.First("_")+1, "");
    if (Model.Contains("T2tt") || Model.Contains("TChiWW_mChi1")) StopMass.Replace(0, StopMass.First("_")+1, "");
    //if (Model=="") StopMass.Replace(0, StopMass.First("_")+1, ""); 
    TString XMass = StopMass;
    StopMass.Replace(StopMass.First("_"), 10000,""); 
    StopMass.ReplaceAll("Sm", "");
    StopMass.ReplaceAll("Xm", "");
    XMass.Replace(0, XMass.First("_")+1, "");
    XMass.ReplaceAll("Xm", "");
    
    mT = StopMass;
    mX = XMass;
      
  }

  cout << "  LHEMassdumper " << Model << " " << mT << " " << mX << endl;
  LHEMassdumper(Model, mT, mX);

}
